- name: Installer Tomcat et déployer sample.war
  hosts: all
  tasks:
    - name: Installer Tomcat
      apt:
        name: tomcat9  # Utilisez le gestionnaire de paquets approprié pour votre système
        state: present

    - name: Copier le fichier WAR
      copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/sample.war
      notify: Redémarrer Tomcat

  handlers:
    - name: Redémarrer Tomcat
      service:
        name: tomcat9  # Utilisez le nom du service Tomcat approprié pour votre système
        state: restarted
        
